export const loadHistory = [
  {
    id: 'cl65ac6zh000028wgh48eyosm',
    title: '湖北微果(중국)',
    description: '고객센터 1:1 라이브 채팅, 영상, 음성 통화 시스템',
    startDate: '2020.01',
    endDate: '',
    tags: ['Nest', 'Prisma', 'React', 'Next', 'Antd', 'Tailwind'],
  },
  {
    id: 'cl62lde9n0000eawgov39yjow',
    title: '카카오 메이커스',
    description:
      '카카오톡 - 더보기 - 메이커스(웹뷰) 결제, 로그인, 상품상세 & 관리자 페이지 프론트앤드개발',
    startDate: '2019.04',
    endDate: '',
    tags: ['Frontend', 'Vue2', 'Nuxt'],
  },
  {
    id: 'cl63u1jzu00072vwge221a6qw',
    title: 'FNG SYSTEM',
    description: '주변 주유소 정보제공 앱서비스',
    startDate: '2018.07',
    endDate: '2019.03',
    tags: ['Frontend', 'Framework7', 'Vue'],
  },
  {
    id: 'cl63u1jzu00002vwgjixl07eh',
    title: '빗썸(대한민국 1등 가상화페 거래소)',
    description: '비트코인 웹결제 서비스',
    startDate: '2017.07',
    endDate: '',
    tags: ['Frontend', 'PHP', 'Javascript'],
  },
  {
    id: 'cl63u1jzu00032vwgf6rqq2oh',
    title: '시시브랜드',
    description: '중국상표출원과 해외상표출원 서비스',
    startDate: '2017.01',
    endDate: '',
    tags: ['Frontend', 'Angular', 'PHP'],
  },
  {
    id: 'cl63u1jzu00102vwgk0gbkzus',
    title: 'SK 주식회사 C&C',
    description: '클라우드 서비스 사이트',
    startDate: '2016.03',
    endDate: '',
    tags: ['Frontend', 'Javascript'],
  },
  {
    id: 'cl63u1jzu00012vwgcczpw4jk',
    title: 'KB인베스트먼트',
    description: '국민은행 모바일 웹사이트 제작',
    startDate: '2015.06',
    endDate: '2015.09',
    tags: ['Javascript'],
  },
  {
    id: 'cl63u1jzu00022vwgaf3batcu',
    title: '일산병원',
    description: '병원 홈페이지 접근성 리뉴얼',
    startDate: '2014.05',
    endDate: '',
    tags: ['Javascript'],
  },
  {
    id: 'cl63u1jzu00082vwg6o7gg0xp',
    title: '현대홈쇼핑',
    description: '모바일웹 쇼핑몰 서비스,첫 반응형 웹사이트 세대',
    startDate: '2012.09',
    endDate: '',
    tags: ['Javascript', 'jQuery'],
  },
  {
    id: 'cl62lgpk70000jawg732fo2qr',
    title: '아사달',
    description: '아사몰 2.0 PHP 개발 & Explorer 6 크로스 브라우징 Table 코딩',
    startDate: '2009.08',
    endDate: '',
    tags: ['PHP', 'Javascript', 'Explorer 6'],
  },
]
