import type { NextPage } from 'next'
import Head from 'next/head'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-24">
        <h1 className="text-3xl font-bold underline text-center">
          Hello world!
        </h1>
      </div>
    </div>
  )
}
